Fixed immediate partial umount for uck-remaster-unpack-{iso,rootfs}. Thanks Fabrizio.

diff --git a/trunk/uck/uck-remaster-unpack-rootfs b/trunk/uck/uck-remaster-unpack-rootfs
--- a/trunk/uck/uck-remaster-unpack-rootfs
+++ b/trunk/uck/uck-remaster-unpack-rootfs
@@ -72,6 +72,8 @@ if [ $use_mount = true ] && check_union_mounts; then
 		union_mount "$SQUASHFS_IMAGE" "$REMASTER_DIR" ||
 			failure "Can't union_mount $REMASTER_DIR"
 	fi
+	# Prevent immediate unmount by cleanup code
+	trap : EXIT
 else
 	if [ $use_mount = true ]; then
 		echo "Cannot use union mounts - using copy instead!"
