Fixed immediate partial umount for uck-remaster-unpack-{iso,rootfs}. Thanks Fabrizio.

diff --git a/uck/uck-remaster-unpack-iso b/uck/uck-remaster-unpack-iso
--- a/uck/uck-remaster-unpack-iso
+++ b/uck/uck-remaster-unpack-iso
@@ -78,6 +78,8 @@ if [ $use_mount = true ] && check_union_mounts; then
 			failure "Can't union_mount $ISO_REMASTER_DIR"
 	fi
 	manifest_diff
+	# Prevent immediate unmount by cleanup code
+	trap : EXIT
 else
 	if [ $use_mount = true ]; then
 		echo "Cannot use union mounts - using copy instead!"
